name: Compress Files from /uncompressed Folder in Main Branch
permissions: write-all

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  compress_files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      # Set up zip utility
      - name: Set up zip utility
        run: sudo apt-get install -y zip

      # Debugging step: List files in /uncompressed folder
      - name: List files in /uncompressed folder
        run: |
          echo "Listing directories under /uncompressed:"
          ls -R uncompressed

      # Find and compress only the most inner directories under /uncompressed
      - name: Find and Compress the Most Inner Directories in /uncompressed
        run: |
          # Find the deepest directory and compress it
          find ./uncompressed -type d | while read dir; do
            # Get the deepest directory based on the folder structure
            depth=$(echo "$dir" | tr -cd '/' | wc -c)
            if [[ $depth -gt 3 ]]; then
              # Create zip with name based on the last 3 directory parts
              zip_name=$(echo "$dir" | sed 's|./uncompressed/||' | tr '/' '-').zip
              zip -r "$zip_name" "$dir"
              echo "Created zip file: $zip_name"
            fi
          done

      # Commit and push the zip files
      - name: Commit and push the zip files
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the token for authentication
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Configure git to use the PAT token for authentication
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          
          # Stage all new zip files
          git add *.zip
          
          # Commit the new zip files
          git commit -m "Add compressed zip files from /uncompressed folder"
          
          # Push the changes
          git push origin
