name: Compress Files from Data Branch
permissions: write-all

on:
  push:
    branches:
      - data
  pull_request:
    branches:
      - data

jobs:
  compress_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout data branch
        uses: actions/checkout@v3
        with:
          ref: data

      - name: Set up zip utility
        run: sudo apt-get install zip

      - name: Find and Compress Files
        run: |
          # Find all subfolders recursively
          find . -type d -exec bash -c 'zip -r "${1//\//-}.zip" "$1"' _ {} \;

      - name: Commit and push the zip files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Stage all new zip files
          git add *.zip
          
          # Commit the new zip files
          git commit -m "Add compressed zip files"
          
          # Push the changes back to the 'data' branch or another branch if needed
          git push origin
