name: Compress Files from /uncompressed Folder in Main Branch
permissions: write-all

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  compress_files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      # Set up zip utility
      - name: Set up zip utility
        run: sudo apt-get install -y zip

      # Debugging step: List files in /uncompressed folder
      - name: List files in /uncompressed folder
        run: |
          echo "Listing directories under /uncompressed:"
          ls -R uncompressed

      # Find and compress only the most inner directories under /uncompressed
      - name: Find and Compress the Most Inner Directories in /uncompressed
        run: |
          # Iterate over all directories in the /uncompressed folder
          find ./uncompressed -type d | while read dir; do
            # Get the depth of the current directory
            depth=$(echo "$dir" | tr -cd '/' | wc -c)
            
            # Only process directories that are the 3rd deepest
            if [[ $depth -eq 4 ]]; then
              # Extract the last three parts of the directory path and replace / with -
              zip_name=$(echo "$dir" | sed 's|./uncompressed/||' | tr '/' '-').zip
              
              # Create a temporary folder to hold the files at the root level
              mkdir temp_zip_dir

              # Copy the files from the 3rd deepest directory to the temp folder
              cp -r "$dir"/* temp_zip_dir/

              cd temp_zip_dir
              # Now zip the contents of temp_zip_dir into a zip at the root of the repo
              zip -r "./$zip_name" *
              cd ..

              # Remove the temporary folder after zipping
              rm -rf temp_zip_dir

              echo "Created zip file: $zip_name"
            fi
          done

      # Commit and push the zip files
      - name: Commit and push the zip files
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the token for authentication
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Configure git to use the PAT token for authentication
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          
          # Stage all new zip files (in the root of the repository)
          git add *.zip
          
          # Commit the new zip files
          git commit -m "Add compressed zip files from /uncompressed folder"
          
          # Push the changes
          git push origin
