name: Compress Files from Data Branch

on:
  push:
    branches:
      - data
  workflow_dispatch:  # Add this line to allow manual trigger

jobs:
  compress_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout data branch
        uses: actions/checkout@v3
        with:
          ref: data

      - name: Print Current Directory
        run: |
          echo "Current directory:"
          pwd
          echo "Files in the repository:"
          ls -R
