name: Compress Files from /uncompressed Folder in Main Branch

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  compress_files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      # Set up zip utility
      - name: Set up zip utility
        run: sudo apt-get install -y zip

      # Debugging step: List files in /uncompressed folder
      - name: List files in /uncompressed folder
        run: |
          echo "Listing directories under /uncompressed:"
          ls -R uncompressed

      # Find and compress only directories under /uncompressed
      - name: Find and Compress Files in /uncompressed
        run: |
          # Find all directories under the /uncompressed folder and compress them
          find ./uncompressed -type d -exec bash -c 'zip -r "${1//\//-}.zip" "$1"' _ {} \;

      # Commit and push the zip files
      - name: Commit and push the zip files
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the token for authentication
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Configure git to use the PAT token for authentication
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          
          # Stage all new zip files
          git add *.zip
          
          # Commit the new zip files
          git commit -m "Add compressed zip files from /uncompressed folder"
          
          # Push the changes back to the 'data' branch
          git push origin data
