name: Generate Files and Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Process data.json
      run: python scripts/process_data.py

    - name: Deploy to gh-pages
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git fetch origin gh-pages || git checkout --orphan gh-pages
        git checkout gh-pages
        rm -rf *
        if [ -d "output" ]; then
          cp -r output/* .
        else
          echo "Output directory does not exist. Exiting."
          exit 1
        fi
        git add .
        git commit -m "Deploy generated files to gh-pages"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages --force
